title: Marian
email: junczys@amu.edu.pl
description: Fast Neural Machine Translation in C++
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marian-nmt.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github: "https://github.com/marian-nmt" # the path to github organisation name!
google_analytics: "UA-109819276-1"

# Build settings
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - commit-and-deploy.sh
  - Makefile
  - "assets/css/_*.less"
  - "*/CHANGELOG*"
  - "*/README*"
  - "*/LICENSE*"
  - "*.json"
  - "*.txt"
  - "*.swp"
  - "*.swo"
  - Doxygen.marian.in
  - marian
gems:
  - "jekyll/scholar"
  - jekyll-last-modified-at

# Theme settings
color_scheme: blue
pygments_css: github
header:
    title_icon: icon_documents_alt
    title_highlighted: Marian
    title_bold: NMT

# Jekyll-schollar settings
scholar:
  style: ./_layouts/acl.csl
  sort_by: year
  order: descending
  source: ./_data
  bibliography_template: bib
  bibliography: amunmt.bib
