name: Website

on:
  push:
    branches:
      - content

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website source
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Build Jekyll
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          custom_opts: '--baseurl /${{ github.event.repository.name }}'

      - name: Test
        run: |
          ls -valphs
          ls -valphs ./_site

# # Generates API docs
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout website source
#         uses: actions/checkout@v2
#         with:
#           submodules: recursive
#       - run: ls -valpsh marian-dev

# # Compiles Marian and ingests CLI options
#     cli:
#       runs-on: ubuntu-latest
#       steps:
#         - name: Checkout website source
#           uses: actions/checkout@v2
#           with:
#             submodules: recursive
#         - run: ls -valpsh marian-dev

# # Deploy to branch
#     deploy:
#       # needs: [jekyll, docs, cli]
#       runs-on: ubuntu-latest
#       steps:
#         - run: git push


      # - name: Install
      #   uses: limjh16/jekyll-action-ts@v2
      #   with:
      #     enable_cache: true
      #     custom_opts: '--baseurl /${{ github.event.repository.name }}'
      #
      # - name: Cache HTML
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/._site
      #     key: jekyll
      #   restore-keys: |
      #     jekyll
      #
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./_site
      #     publish_branch: gh-pages
      #     enable_jekyll: false # prevents GitHub running Jekyll
